export const ACTION_TRY_BUY_GENERATOR = 'ACTION_TRY_BUY_GENERATOR';
export const ACTION_TRY_SELL_GENERATOR = 'ACTION_TRY_SELL_GENERATOR';
export const ACTION_GENERATE_FROM_POINTER = 'ACTION_GENERATE_FROM_POINTER';
export const ACTION_GAME_TICK = 'ACTION_GAME_TICK';
export const ACTION_GAME_SAVE = 'ACTION_GAME_SAVE';
export const ACTION_GAME_LOAD = 'ACTION_GAME_LOAD';